/**
 * Kysera benchmark runner.
 *
 * Runs every suite sequentially on the main thread, prints progress, writes
 * bench/RESULTS.md and echoes the full report to stdout.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { renderEnvironmentHeader, renderQueryCountSection, renderSuiteTable } from './report.js'
import type { SuiteTable } from './runner.js'
import { runBuilderChainSuite } from './suites/builder-chain.js'
import { runDalOverheadSuite } from './suites/dal-overhead.js'
import { runPaginationSuite } from './suites/pagination.js'
import { runQueryCountSuite } from './suites/query-count.js'
import { runRepositoryHotPathSuite } from './suites/repository-hot-path.js'

async function main(): Promise<void> {
  const startedAt = Date.now()
  const sections: string[] = []
  let sectionIndex = 0

  const pushSuites = (suites: SuiteTable[]): void => {
    for (const suite of suites) {
      sectionIndex += 1
      sections.push(renderSuiteTable(suite, sectionIndex))
    }
  }

  console.error('[bench] builder-chain overhead …')
  pushSuites(await runBuilderChainSuite())

  console.error('[bench] repository hot path …')
  pushSuites(await runRepositoryHotPathSuite())

  console.error('[bench] mutation round-trip query count …')
  const queryCount = await runQueryCountSuite()
  sectionIndex += 1
  sections.push(renderQueryCountSection(sectionIndex, queryCount.entries, queryCount.notes))

  console.error('[bench] DAL overhead …')
  pushSuites([await runDalOverheadSuite()])

  console.error('[bench] pagination …')
  pushSuites([await runPaginationSuite()])

  const elapsedSec = ((Date.now() - startedAt) / 1000).toFixed(1)
  const report = [
    '# Kysera benchmark results',
    '',
    '<!-- Generated by `pnpm bench` (bench/src/index.ts). Do not edit by hand. -->',
    '',
    renderEnvironmentHeader(),
    '',
    ...sections.flatMap(section => [section, '']),
    `_Total benchmark wall time: ${elapsedSec} s._`,
    ''
  ].join('\n')

  const resultsPath = fileURLToPath(new URL('../RESULTS.md', import.meta.url))
  writeFileSync(resultsPath, report)
  console.error(`[bench] wrote ${resultsPath}`)
  console.log(report)
}

main().catch((error: unknown) => {
  console.error('[bench] FAILED:', error)
  process.exitCode = 1
})
